[package]
name = "crust"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9"
derive_more = "0.99"
clap = { version = "4.5.4", features = ["derive"] }
ariadne = { version = "0.4", features = ["auto-color"] }
