[package]
name = "crust"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9"
serde_json = "1.0"
derive_more = "0.99"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.4", features = ["derive"] }
ariadne = { version = "0.4", features = ["auto-color"] }
